runtime: python312

env_variables:
  INSTANCE_CONNECTION_NAME: "systems-design-assignment:europe-west2:restaurantapp"
  GOOGLE_CLOUD_PROJECT: "systems-design-assignment"
  FLASK_SECRET_KEY: "some-long-random-string"
  AUDIT_FUNCTION_URL: "https://order-audit-log-390833686250.europe-west1.run.app"
  
entrypoint: gunicorn -b :$PORT main:app

handlers:
  - url: /static
    static_dir: static
  - url: /.*
    script: auto
